### ISSUE TITLE
NaN ~ undefined

### ISSUE THREAD

**Issue by iver56** [thormartin91/GradeAverage#1]
The bookmarklet doesn't work for me. Tried in FF and Chrome. This is what I see:

![image](https://cloud.githubusercontent.com/assets/1470603/17719261/7ec72084-6419-11e6-82be-7c0d6465708e.png)

**Comment by thormartin91** [comment]
Caused by courses without a single grade. "Bestått/ikke bestått". Fix on the way :)

**Comment by thormartin91** [comment]
Can you give it a try now, @iver56 ?
(need to re-add the bookmark https://thormartin91.github.io/GradeAverage)

**Comment by iver56** [comment]
Works
